### ISSUE TITLE
Feature request: `around/p` combinator

### ISSUE THREAD

**Issue by jackfirth** [lexi-lambda/megaparsack#7]
Often I want a parser that's like some parser `p`, but with some ignored prefix or suffix. I'd like an `around/p` combinator to make this situation a little more readable:

```racket
(define (around/p p #:before [before void/p] #:after [after void/p])
  (do before [v <- p] after (pure v)))
```

As with #5, #4, and #3 I've implemented this and would like to know if a PR would be welcome.

**Comment by lexi-lambda** [comment]
Yeah, I’ve thought about this a bit. The thing is, you only need applicative power to write this, and in Haskell you would just write it like `before *> p <* after`, which works in much more general ways than a specific `around/p` combinator. You can do stuff like `a *> b *> c *> x <* d`, for example, and if you want to use the result of two parsers, you can do stuff like `(,) <$> a *> x <*> y <* b`. The syntax is perhaps not ideal, but it’s really nice for the common cases.

The old parsack library did this with a [`parser-seq`](http://docs.racket-lang.org/parsack/index.html#%28form._%28%28lib._parsack%2Fmain..rkt%29._parser-seq%29%29) macro. Maybe it would be possible to come up with a similar notation for all applicatives instead of adding something parser-specific?

**Comment by jackfirth** [comment]
I ended up creating `seq` and `seq0` for all applicatives in my projects:

```racket
(define (seq . applicatives)
  (map last (apply (pure list) applicatives))
(define (seq0 . applicatives)
  (map first (apply (pure list) applicatives))
```

This works well enough. It's a *little* obtuse for adding parens / brackets / etc. around parsers, so I had an idea for something like this:

```racket
(struct delimiters (left right) #:transparent)
(define paren-delimiters (delimiters (char/p #\() (char/p #\))))
(define bracket-delimiters (delimiters (char/p #\[) (char/p #\])))

(define (delimit/p prsr delim)
  (seq (delimiters-left delim) (seq0 prsr (delimiters-right delim))))
```

This makes adding wrapper characters around parsers pleasantly easy to write and read:

```racket
(define int-array/p
  (delimit/p (many/p integer/p #:sep (char/p #\,))
             bracket-delimiters))
```

I like it, but it might be overkill for megaparsack. What do you think?

**Comment by lexi-lambda** [comment]
Yeah, I’m not super fond of it because it seems to add a lot of boilerplate without improving very much on just writing the code that happens under the hood. Is that use of `delimit/p` really clearer or easier to write than something like this?

```racket
(define int-array/p
  (select (char/p #\() !(many/p integer/p #:sep (char/p #\,)) (char/p #\)))
```

Especially given that you omit writing all the definitions. I don’t think `select` is the right name for that macro, and it might not even be the right syntax, but I think this is something that can be solved in a much more general way without sacrificing clarity.

**Comment by jackfirth** [comment]
There's a lot of potential for applicative syntaxes, but I'd rather use something that directly names what I'm trying to do with a first-class concept rather than implicitly allowing it through other means. First-class delimiters means I can easily write this:

```
(define (string-delimiters str)
  (delimiters (string/p str)
              (string/p (list->string (reverse (string->list str))))))

(parse-string (delimit/p integer/p (string-delimiters ".oO--"))
              ".oO--123--Oo.")
```

**Comment by lexi-lambda** [comment]
You just don’t get any abstraction power from wrapping delimiters up in to a delimiters struct. There are no useful operations on “delimiters” aside from `delimit/p`. I think “first class delimiters” is a weird concept to want when delimiters are such a hyper-specific concept already. I don’t expect people to be writing delimiter combinator libraries anytime soon.

More to the point, though, I don’t think I find a huge amount of value in something like that, even a simpler version of that. It’s such a specific use case that I don’t really expect providing it in megaparsack itself would save anyone very much time *if* we had good applicative notation, too.

**Comment by jackfirth** [comment]
I was imagining megaparsack would provide common delimiters out of the box, in which case you don't have to define `paren-delimiters` as a client of the library. That's the smoothest experience I can imagine for users asking "how do I parse things wrapped in parens, brackets, braces, etc.?" I'd make use of it in some of the parsers I'm writing for certain HTTP headers, for example.

I do agree that better syntaxes for applicatives would be much more useful, so I'll close this issue for now.
